Repository luslab/luslab-nf-modules, pull requests merged in 2020-11, with the labels that each got.

#114 add publishdir to cut and sort processes
  tools/luslab_linux_tools/VERSION
  tools/luslab_linux_tools/main.nf
Labels: enhancement

#115 Add genomecov process for calculating coverage using bam file and scale normalisation
  configs/module-defaults.config
  tools/bedtools/VERSION
  tools/bedtools/main.nf
  tools/bedtools/test/main.nf
Labels: enhancement

#112 add mafft module
  .github/workflows/modules-testing.yml
  configs/module-defaults.config
  tools/mafft/VERSION
  tools/mafft/main.nf
  tools/mafft/test/main.nf
  tools/mafft/test/nextflow.config
Labels: enhancement

#113 add emboss (seqret) and phyml
  .github/workflows/modules-testing.yml
  configs/module-defaults.config
  test_data/fasta/insulin.afa
  test_data/fasta/insulin.phylip
  tools/emboss/VERSION
  tools/emboss/main.nf
  tools/emboss/test/main.nf
  tools/emboss/test/nextflow.config
  tools/phyml/VERSION
  tools/phyml/main.nf
  tools/phyml/test/main.nf
  tools/phyml/test/nextflow.config
Labels: enhancement

#116 fixed paired_bam_to_bedgraph discretisation issue
  workflows/bed_flows/main.nf
  workflows/bed_flows/test/main.nf
Labels: bug

#118 Added cluster labels for common queue and resource levels
  .github/workflows/modules-testing.yml
  .github/workflows/workflow-testing.yml
  configs/crick.config
  configs/luslab-base.config
  main.nf
  nextflow.config
  tools/luslab_util/main.nf
  workflows/resource_allocation/main.nf
  workflows/resource_allocation/test/main.nf
  workflows/resource_allocation/test/nextflow.config
Labels: enhancement

#119 Added review section to PR template and tidied formatting
  .github/pull_request_template.md
Labels: documentation, non-functional
