Repository luslab/luslab-nf-modules, pull requests merged in 2020-12, with the labels that each got.

#121 Feat mod augustus
  .github/workflows/modules-testing.yml
  configs/module-defaults.config
  test_data/augustus/s_cerevisiae_custom/changes_from_defaults.txt
  test_data/augustus/s_cerevisiae_custom/s_cerevisiae_custom_exon_probs.pbl
  test_data/augustus/s_cerevisiae_custom/s_cerevisiae_custom_igenic_probs.pbl
  test_data/augustus/s_cerevisiae_custom/s_cerevisiae_custom_intron_probs.pbl
  test_data/augustus/s_cerevisiae_custom/s_cerevisiae_custom_metapars.cfg
  test_data/augustus/s_cerevisiae_custom/s_cerevisiae_custom_parameters.cfg
  test_data/augustus/s_cerevisiae_custom/s_cerevisiae_custom_weightmatrix.txt
  tools/augustus/VERSION
  tools/augustus/main.nf
  tools/augustus/test/main.nf
  tools/augustus/test/nextflow.config
Labels: enhancement

#122 change guppy testfile to speed up git action
  test_data/fast5/sample10.fast5
  test_data/fast5/sample11.fast5
  test_data/fast5/sample3.fast5
  test_data/fast5/sample4.fast5
  test_data/fast5/sample5.fast5
  test_data/fast5/sample6.fast5
  test_data/fast5/sample7.fast5
  test_data/fast5/sample8.fast5
  test_data/fast5/sample9.fast5
  tools/guppy/test/main.nf
Labels: non-functional

#124 add emit option for tuple of meta and report file for structural compatibility with annotate metadata workflow
  tools/deeptools/VERSION
  tools/deeptools/main.nf
  tools/deeptools/test/main.nf
Labels: enhancement

#125 added emit to fit with custom awk for annotation
  tools/deeptools/VERSION
  tools/deeptools/main.nf
  tools/deeptools/test/main.nf
Labels: enhancement

#128 update guppy networking packages
  tools/guppy/Dockerfile.cpu
  tools/guppy/Dockerfile.gpu
  tools/guppy/VERSION
  tools/paraclu/Dockerfile
  tools/paraclu/VERSION
Labels: bug

#129 add emit for fragment csv only with no meta
  tools/deeptools/VERSION
  tools/deeptools/main.nf
  tools/deeptools/test/main.nf
Labels: enhancement

#130 Feat deeptools
  tools/peka/Dockerfile
  tools/peka/VERSION
  tools/peka/main.nf
Labels: bug
