Repository luslab/luslab-nf-modules, pull requests merged in 2020-08, with the labels that each got.

#46 convert cutadapt module to match new metadata format
  configs/module-defaults.config
  test_data/cutadapt/sample1_r1.fq.gz
  test_data/cutadapt/sample1_r2.fq.gz
  test_data/cutadapt/sample2_r1.fq.gz
  test_data/cutadapt/sample2_r2.fq.gz
  test_data/cutadapt/sample3_r1.fq.gz
  test_data/cutadapt/sample3_r2.fq.gz
  test_data/cutadapt/sample4_r1.fq.gz
  test_data/cutadapt/sample4_r2.fq.gz
  test_data/cutadapt/sample5_r1.fq.gz
  test_data/cutadapt/sample5_r2.fq.gz
  test_data/cutadapt/sample6_r1.fq.gz
  test_data/cutadapt/sample6_r2.fq.gz
  tools/cutadapt/main.nf
  tools/cutadapt/test/main.nf
  tools/cutadapt/test/nextflow.config
Labels: enhancement

#43 tantan module for the long-read assembly pipeline.
  .github/workflows/docker-linting.yml
  .github/workflows/modules-testing.yml
  configs/module-defaults.config
  tools/tantan/Dockerfile
  tools/tantan/main.nf
  tools/tantan/test/main.nf
  tools/tantan/test/nextflow.config
Labels: enhancement

#50 Added minimap2 docker file
  tools/minimap2/Dockerfile
Labels: bug, enhancement

#51 Fixing module build fail error
  .github/workflows/modules-testing.yml
  tools/icount/Dockerfile
  tools/paraclu/Dockerfile
Labels: bug

#44 Feat mod metadata
  test_data/fastq/smartseq2/ss11_123fq/WTCHG_524615_201106_1.sub.fastq.gz
  test_data/fastq/smartseq2/ss11_123fq/WTCHG_524615_201106_2.sub.fastq.gz
  test_data/fastq/smartseq2/ss11_123fq/WTCHG_524615_201191_1.sub.fastq.gz
  test_data/fastq/smartseq2/ss11_123fq/WTCHG_524615_201191_2.sub.fastq.gz
  test_data/fastq/smartseq2/ss15_123fq/WTCHG_528508_201108_1.sub.fastq.gz
  test_data/fastq/smartseq2/ss15_123fq/WTCHG_528508_201108_2.sub.fastq.gz
  test_data/fastq/smartseq2/ss15_123fq/WTCHG_528508_201189_1.sub.fastq.gz
  test_data/fastq/smartseq2/ss15_123fq/WTCHG_528508_201189_2.sub.fastq.gz
  test_data/fastq/smartseq2/ss8_9/TSS_P1_A1-1234.sub.fastq.gz
  test_data/fastq/smartseq2/ss8_9/TSS_P1_A10-1234.sub.fastq.gz
  test_data/metadata/smartseq_test.csv
  tools/metadata/main.nf
  tools/metadata/test/main.nf
Labels: enhancement

#55 fix output from samtools sort
  tools/samtools/main.nf
Labels: enhancement

#56 Feat mod velocyto
  tools/velocyto/main.nf
  tools/velocyto/test/main.nf
  tools/velocyto/test/nextflow.config
Labels: enhancement

#58 update homer to new module structure
  .github/workflows/docker-build-push.yml
  .github/workflows/docker-linting.yml
  configs/module-defaults.config
  tools/homer/Dockerfile
  tools/homer/environment.yml
  tools/homer/main.nf
  tools/homer/test/main.nf
  tools/homer/test/nextflow.config
Labels: enhancement

#59 Feat mod bedtools
  .github/workflows/docker-build-push.yml
  .github/workflows/docker-linting.yml
  configs/module-defaults.config
  tools/bedtools/Dockerfile
  tools/bedtools/environment.yml
  tools/bedtools/main.nf
  tools/bedtools/test/main.nf
Labels: enhancement

#60 Feat mod homer
  tools/homer/main.nf
Labels: bug

#61 Updated cutadapt and fastqc
  .github/workflows/docker-build-push.yml
  .github/workflows/docker-linting.yml
  configs/module-defaults.config
  tools/cutadapt/Dockerfile
  tools/cutadapt/environment.yml
  tools/cutadapt/main.nf
  tools/fastqc/Dockerfile
  tools/fastqc/environment.yml
  tools/fastqc/main.nf
  tools/fastqc/test/input/readfile1_r1.fq.gz
  tools/fastqc/test/input/readfile1_r2.fq.gz
  tools/fastqc/test/input/readfile2_r1.fq.gz
  tools/fastqc/test/input/readfile2_r2.fq.gz
  tools/fastqc/test/input/readfile3_r1.fq.gz
  tools/fastqc/test/input/readfile3_r2.fq.gz
  tools/fastqc/test/input/readfile4_r1.fq.gz
  tools/fastqc/test/input/readfile4_r2.fq.gz
  tools/fastqc/test/input/readfile5_r1.fq.gz
  tools/fastqc/test/input/readfile5_r2.fq.gz
  tools/fastqc/test/input/readfile6_r1.fq.gz
  tools/fastqc/test/input/readfile6_r2.fq.gz
  tools/fastqc/test/main.nf
  tools/fastqc/test/nextflow.config
Labels: enhancement

#64 Updated umitools module to match latest syntax
  configs/module-defaults.config
  test_data/umi_tools/sample1.bai
  test_data/umi_tools/sample1.bam
  test_data/umi_tools/sample2.bai
  test_data/umi_tools/sample2.bam
  tools/umi_tools/main.nf
  tools/umi_tools/test/main.nf
  tools/umi_tools/test/nextflow.config
Labels: enhancement

#66 Added bowtie2 module options for sorted, indexed bam and to output unmapped reads
  configs/module-defaults.config
  tools/bowtie2/environment.yml
  tools/bowtie2/main.nf
  tools/bowtie2/test/main.nf
Labels: enhancement
