Repository luslab/luslab-nf-modules, pull requests merged in 2020-10, with the labels that each got.

#81 Feat mod linuxtools
  configs/module-defaults.config
  test_data/luslab_linux_tools/test.txt
  tools/luslab_linux_tools/main.nf
  tools/luslab_linux_tools/test/main.nf
  tools/luslab_linux_tools/test/nextflow.config
  tools/samtools/test/main.nf
  tools/seqtk/test/main.nf
  workflows/fast_flows/test/main.nf
Labels: enhancement

#82 Added tags to processes
  .github/workflows/docker-build-push.yml
  .github/workflows/docker-linting.yml
  tools/bedtools/main.nf
  tools/bowtie2/main.nf
  tools/cutadapt/main.nf
  tools/fastqc/main.nf
  tools/flye/main.nf
  tools/get_crosslinks/main.nf
  tools/get_crosslinks_coverage/main.nf
  tools/guppy/main.nf
  tools/hisat2/Dockerfile
  tools/hisat2/main.nf
  tools/homer/main.nf
  tools/htseq/main.nf
  tools/icount/main.nf
  tools/luslab_genome_tools/main.nf
  tools/luslab_linux_tools/main.nf
  tools/macs2/main.nf
  tools/minimap2/Dockerfile
  tools/minimap2/main.nf
  tools/minionqc/main.nf
  tools/multiqc/main.nf
  tools/nanoplot/Dockerfile
  tools/nanoplot/main.nf
  tools/paraclu/main.nf
  tools/peka/main.nf
  tools/samtools/Dockerfile
  tools/samtools/main.nf
  tools/seqtk/Dockerfile
  tools/seqtk/main.nf
  tools/star/main.nf
  tools/tantan/main.nf
  tools/umi_tools/main.nf
  tools/velocyto/main.nf
Labels: enhancement

#83 Feat mod metadata
  test_data/fastq/10x/seq1/sample1/seq1_sample1_R1.fastq.gz
  test_data/fastq/10x/seq1/sample1/seq1_sample1_R2.fastq.gz
  test_data/fastq/10x/seq1/sample2/seq1_sample2_R1.fastq.gz
  test_data/fastq/10x/seq1/sample2/seq1_sample2_R2.fastq.gz
  test_data/fastq/10x/seq2/sample1/seq2_sample1_R1.fastq.gz
  test_data/fastq/10x/seq2/sample1/seq2_sample1_R2.fastq.gz
  test_data/fastq/10x/seq2/sample2/seq2_sample2_R1.fastq.gz
  test_data/fastq/10x/seq2/sample2/seq2_sample2_R2.fastq.gz
  test_data/metadata/10x_test.csv
  tools/metadata/main.nf
  tools/metadata/test/main.nf
Labels: enhancement

#86 Added a test condition to check for a VERSION file during testing (only triggers if dockerfile exists)
  .github/workflows/modules-testing.yml
  tools/seacr/VERSION
Labels: bug, enhancement

#89 Updated awk module to add option to not write to an output file in for more flexibility
  configs/module-defaults.config
  tools/luslab_linux_tools/main.nf
  tools/luslab_linux_tools/test/main.nf
Labels: enhancement

#88 Feat mod containers
  .github/workflows/docker-build-push.yml
  .github/workflows/docker-linting.yml
  tools/bowtie2/Dockerfile
  tools/bowtie2/VERSION
  tools/bowtie2/environment.yml
  tools/bowtie2/main.nf
  tools/get_crosslinks/Dockerfile
  tools/get_crosslinks/VERSION
  tools/get_crosslinks/environment.yml
  tools/get_crosslinks/main.nf
  tools/get_crosslinks_coverage/Dockerfile
  tools/get_crosslinks_coverage/VERSION
  tools/get_crosslinks_coverage/environment.yml
  tools/get_crosslinks_coverage/main.nf
  tools/hisat2/environment.yml
  tools/icount/Dockerfile
  tools/icount/VERSION
  tools/icount/environment.yml
  tools/icount/main.nf
  tools/paraclu/main.nf
  tools/samtools/environment.yml
  tools/seacr/Dockerfile
  tools/seacr/VERSION
  tools/seacr/environment.yml
  tools/seacr/main.nf
  tools/star/Dockerfile
  tools/star/VERSION
  tools/star/environment.yml
  tools/star/main.nf
  tools/umi_tools/Dockerfile
  tools/umi_tools/VERSION
  tools/umi_tools/environment.yml
  tools/umi_tools/main.nf
Labels: enhancement

#94 samtools_index changed to agreed bam_bai channel format + bam_flows module added
  .github/workflows/workflow-testing.yml
  configs/module-defaults.config
  tools/samtools/main.nf
  tools/samtools/test/main.nf
  workflows/bam_flows/main.nf
  workflows/bam_flows/test/main.nf
  workflows/bam_flows/test/nextflow.config
Labels: enhancement

#95 Added bam metadata module that kicks out bam/bai in the correct chann…
  test_data/metadata/bam_test.csv
  tools/metadata/main.nf
  tools/metadata/test/main.nf
  tools/samtools/VERSION
Labels: enhancement

#96 Pull request template
  .github/pull_request_template.md
Labels: enhancement

#104 Small changes
  .github/pull_request_template.md
  configs/crick.config
  tools/samtools/main.nf
  tools/samtools/test/main.nf
  workflows/fast_flows/main.nf
Labels: bug
